# reference:
#   https://github.com/brookslybrand/remix-gh-pages/blob/main/.github/workflows/build-deploy.yml#L39C1-L40C1
name: github pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/configure-pages@v4  # configured with terraform

      - uses: pnpm/action-setup@v4 # https://github.com/pnpm/action-setup
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: "20"
          cache: "pnpm"

      - run: pnpm install

      #- run: pnpm lint

      - run: pnpm build

      #- run: |
      #    echo www.tmtk.net > build/client/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/client"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
