name: github pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/configure-pages@v4  # configured with terraform

      - uses: pnpm/action-setup@v4 # https://github.com/pnpm/action-setup
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v2
        name: Install Node.js
        with:
          node-version: "20"
          cache: "pnpm"

      - run: pnpm install

      #- run: pnpm lint

      - run: pnpm build

      #- run: |
      #    mkdir -p ./out
      #    touch ./out/.nojekyll

      #
      # NOTE:
      #   Visit https://github.com/tmtk75/my-site/settings/actions
      #   Select Workflow permissions -> Read and write permissions.
      #
      #- uses: peaceiris/actions-gh-pages@v4
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./build/client
      #    #cname: www.tmtk.net

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "build/client"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
